/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package laboratorio6;
import java.util.*;
import javax.swing.JOptionPane;
public class Conjuntos extends javax.swing.JFrame {
    private Set<String> Web;
    private Set<String> Java;
    private Set<String> Celulares;
    private SetFactory<String> factory;
    private int interseccion = 0;
    
    public Conjuntos() {
        factory = new SetFactory();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        rdbHashSet = new javax.swing.JRadioButton();
        rdbTreeSet = new javax.swing.JRadioButton();
        rdbLinkedHashSet = new javax.swing.JRadioButton();
        lblSeleccion = new javax.swing.JLabel();
        btnConjunto = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        lblIngreso = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        chkWeb = new javax.swing.JCheckBox();
        chkJava = new javax.swing.JCheckBox();
        chkCelulares = new javax.swing.JCheckBox();
        btnDesarrollador = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        lblIngreso1 = new javax.swing.JLabel();
        lblRes1 = new javax.swing.JLabel();
        lblRes2 = new javax.swing.JLabel();
        lblRes3 = new javax.swing.JLabel();
        lblRes4 = new javax.swing.JLabel();
        lblRes5 = new javax.swing.JLabel();
        lblRes6 = new javax.swing.JLabel();
        lblRes7 = new javax.swing.JLabel();
        lblRes8 = new javax.swing.JLabel();
        lblAtencion = new javax.swing.JLabel();
        btnMayor = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        buttonGroup1.add(rdbHashSet);
        rdbHashSet.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        rdbHashSet.setText("HashSet");
        rdbHashSet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbHashSetActionPerformed(evt);
            }
        });

        buttonGroup1.add(rdbTreeSet);
        rdbTreeSet.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        rdbTreeSet.setText("TreeSet");
        rdbTreeSet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbTreeSetActionPerformed(evt);
            }
        });

        buttonGroup1.add(rdbLinkedHashSet);
        rdbLinkedHashSet.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        rdbLinkedHashSet.setText("LinkedHashSet");
        rdbLinkedHashSet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbLinkedHashSetActionPerformed(evt);
            }
        });

        lblSeleccion.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        lblSeleccion.setForeground(new java.awt.Color(0, 51, 204));
        lblSeleccion.setText("Seleccione una Implementación");

        btnConjunto.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        btnConjunto.setText("CREAR CONJUNTOS");
        btnConjunto.setEnabled(false);
        btnConjunto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConjuntoActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setForeground(new java.awt.Color(0, 153, 153));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 8, Short.MAX_VALUE)
        );

        lblIngreso.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        lblIngreso.setForeground(new java.awt.Color(0, 51, 204));
        lblIngreso.setText("Ingreso de Nombres");

        txtNombre.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtNombre.setEnabled(false);
        txtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreActionPerformed(evt);
            }
        });

        chkWeb.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        chkWeb.setText("Web");
        chkWeb.setEnabled(false);
        chkWeb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkWebActionPerformed(evt);
            }
        });

        chkJava.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        chkJava.setText("Java");
        chkJava.setEnabled(false);
        chkJava.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkJavaActionPerformed(evt);
            }
        });

        chkCelulares.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        chkCelulares.setText("Celulares");
        chkCelulares.setEnabled(false);
        chkCelulares.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkCelularesActionPerformed(evt);
            }
        });

        btnDesarrollador.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        btnDesarrollador.setText("NUEVO DESARROLLADOR");
        btnDesarrollador.setEnabled(false);
        btnDesarrollador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDesarrolladorActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(0, 153, 153));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.setForeground(new java.awt.Color(0, 153, 153));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 8, Short.MAX_VALUE)
        );

        lblIngreso1.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        lblIngreso1.setForeground(new java.awt.Color(0, 51, 204));
        lblIngreso1.setText("Resultados");

        lblRes1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblRes1.setText("Desarrolladores con Experiencia en Java, Web y Celulares:");

        lblRes2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblRes2.setText("Desarrolladores con Experiencia en Java:");

        lblRes3.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblRes3.setText("Desarrolladores con Experiencia en Web y Celulares:");

        lblRes4.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblRes4.setText("Desarrolladores con Experiencia en Web o Celulares:");

        lblRes5.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblRes5.setText("0");

        lblRes6.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblRes6.setText("0");

        lblRes7.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblRes7.setText("0");

        lblRes8.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblRes8.setText("0");

        lblAtencion.setText("ATENCION");

        btnMayor.setText("Conjunto Mayor");
        btnMayor.setEnabled(false);
        btnMayor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMayorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addContainerGap()
                                    .addComponent(btnConjunto, javax.swing.GroupLayout.PREFERRED_SIZE, 344, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(23, 23, 23)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(lblSeleccion)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(lblAtencion))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(rdbHashSet)
                                            .addGap(18, 18, 18)
                                            .addComponent(rdbTreeSet)
                                            .addGap(18, 18, 18)
                                            .addComponent(rdbLinkedHashSet)))))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblIngreso)
                                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnDesarrollador, javax.swing.GroupLayout.PREFERRED_SIZE, 344, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblIngreso1)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(16, 16, 16)
                                        .addComponent(chkWeb)
                                        .addGap(48, 48, 48)
                                        .addComponent(chkJava)
                                        .addGap(43, 43, 43)
                                        .addComponent(chkCelulares))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblRes2)
                                            .addComponent(lblRes1)
                                            .addComponent(lblRes3)
                                            .addComponent(lblRes4))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblRes8)
                                            .addComponent(lblRes7)
                                            .addComponent(lblRes5)
                                            .addComponent(lblRes6))))))
                        .addGap(0, 19, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnMayor)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSeleccion)
                    .addComponent(lblAtencion))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rdbHashSet)
                    .addComponent(rdbTreeSet)
                    .addComponent(rdbLinkedHashSet))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnConjunto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblIngreso)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chkWeb)
                    .addComponent(chkJava)
                    .addComponent(chkCelulares))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnDesarrollador)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblIngreso1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRes1)
                    .addComponent(lblRes5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRes2)
                    .addComponent(lblRes6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRes3)
                    .addComponent(lblRes7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRes4)
                    .addComponent(lblRes8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(btnMayor)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rdbHashSetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbHashSetActionPerformed
        // TODO add your handling code here:
        btnConjunto.setEnabled(true);
    }//GEN-LAST:event_rdbHashSetActionPerformed

    private void rdbTreeSetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbTreeSetActionPerformed
        // TODO add your handling code here:
        btnConjunto.setEnabled(true);
    }//GEN-LAST:event_rdbTreeSetActionPerformed

    private void rdbLinkedHashSetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbLinkedHashSetActionPerformed
        // TODO add your handling code here:
        btnConjunto.setEnabled(true);
    }//GEN-LAST:event_rdbLinkedHashSetActionPerformed

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreActionPerformed

    private void chkWebActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkWebActionPerformed
        // TODO add your handling code here:
        btnDesarrollador.setEnabled(true);
    }//GEN-LAST:event_chkWebActionPerformed

    private void chkJavaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkJavaActionPerformed
        // TODO add your handling code here:
        btnDesarrollador.setEnabled(true);
    }//GEN-LAST:event_chkJavaActionPerformed

    private void chkCelularesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkCelularesActionPerformed
        // TODO add your handling code here:
        btnDesarrollador.setEnabled(true);
    }//GEN-LAST:event_chkCelularesActionPerformed

    private void btnDesarrolladorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDesarrolladorActionPerformed
        // TODO add your handling code here:
        btnConjunto.setEnabled(false);
        String persona = txtNombre.getText();
        
        
        if(chkWeb.isSelected() && chkJava.isSelected() && chkCelulares.isSelected()){
            Web.add(persona);
            Java.add(persona);
            Celulares.add(persona);
            lblRes5.setText(Web.size()+Java.size()+Celulares.size()+"");
            lblRes6.setText(Java.size()+"");
            interseccion = interseccion + 1;
            lblRes7.setText(interseccion+"");
        }
        else if(chkJava.isSelected()){
            Java.add(persona);
            lblRes6.setText(Java.size()+"");
        }
        else if(chkWeb.isSelected() && chkCelulares.isSelected()){
            Web.add(persona);
            Celulares.add(persona);
            lblRes7.setText(interseccion+"");
            interseccion = interseccion + 1;
        }
        if(chkWeb.isSelected() || chkCelulares.isSelected()){
            if(!(chkWeb.isSelected() && chkCelulares.isSelected())){
                if(chkWeb.isSelected()){
                    Web.add(persona);
                    if(Celulares.contains(persona))
                        interseccion = interseccion + 1;
                }
                else if(chkCelulares.isSelected()){
                    Celulares.add(persona);
                    if(Web.contains(persona))
                        interseccion = interseccion + 1;
                }
            }
            lblRes7.setText(interseccion+"");
            lblRes8.setText((Web.size()+Celulares.size()-interseccion)+"");
        }
        
        lblAtencion.setText(Web.size()+"");
        txtNombre.setText("");
        chkWeb.setSelected(false);
        chkJava.setSelected(false);
        chkCelulares.setSelected(false);
        btnMayor.setEnabled(true);

        
    }//GEN-LAST:event_btnDesarrolladorActionPerformed

    private void btnConjuntoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConjuntoActionPerformed
        // TODO add your handling code here:
        btnConjunto.setEnabled(false);
        rdbHashSet.setEnabled(false);
        rdbTreeSet.setEnabled(false);
        rdbLinkedHashSet.setEnabled(false);
        if(rdbHashSet.isSelected()){
            Web = factory.getSet("HS");
            Java = factory.getSet("HS");
            Celulares = factory.getSet("HS");
        }
        else if(rdbTreeSet.isSelected()){
            Web = factory.getSet("TS");
            Java = factory.getSet("TS");
            Celulares = factory.getSet("TS");
        }
        else if(rdbLinkedHashSet.isSelected()){
            Web = factory.getSet("LS");
            Java = factory.getSet("LS");
            Celulares = factory.getSet("LS");
        }
        
        txtNombre.setEnabled(true);
        chkWeb.setEnabled(true);
        chkJava.setEnabled(true);
        chkCelulares.setEnabled(true);
        
    }//GEN-LAST:event_btnConjuntoActionPerformed

    private void btnMayorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMayorActionPerformed
        // TODO add your handling code here:
        if(Web.size()>Celulares.size()){
            if(Web.size()>Java.size())
                JOptionPane.showMessageDialog(null, "Conjunto Web:\n"+Web.toString());
        }
        if(Celulares.size()>Web.size()){
            if(Celulares.size()>Java.size()){
                JOptionPane.showMessageDialog(null, "Conjunto Celulares:\n"+Celulares.toString());
            }
        }
        if(Java.size()>Web.size()){
            if(Java.size()>Celulares.size()){
                JOptionPane.showMessageDialog(null, "Conjunto Java:\n"+Java.toString());
            }
        }
    }//GEN-LAST:event_btnMayorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Conjuntos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Conjuntos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Conjuntos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Conjuntos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Conjuntos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConjunto;
    private javax.swing.JButton btnDesarrollador;
    private javax.swing.JButton btnMayor;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JCheckBox chkCelulares;
    private javax.swing.JCheckBox chkJava;
    private javax.swing.JCheckBox chkWeb;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblAtencion;
    private javax.swing.JLabel lblIngreso;
    private javax.swing.JLabel lblIngreso1;
    private javax.swing.JLabel lblRes1;
    private javax.swing.JLabel lblRes2;
    private javax.swing.JLabel lblRes3;
    private javax.swing.JLabel lblRes4;
    private javax.swing.JLabel lblRes5;
    private javax.swing.JLabel lblRes6;
    private javax.swing.JLabel lblRes7;
    private javax.swing.JLabel lblRes8;
    private javax.swing.JLabel lblSeleccion;
    private javax.swing.JRadioButton rdbHashSet;
    private javax.swing.JRadioButton rdbLinkedHashSet;
    private javax.swing.JRadioButton rdbTreeSet;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
